export const products = [
    {
        name: 'Men Round Neck Pure Cotton T-shirt',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 80,
        category: 'Men',
        subCategory: 'Topwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: true,
        featured: true,
        stock: 50,
        images: ['https://res.cloudinary.com/demo/image/upload/sample.jpg'],
    },
    {
        name: 'Men Tapered Fit Flat-Front Trousers',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear.',
        price: 72,
        category: 'Men',
        subCategory: 'Bottomwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: true,
        featured: true,
        stock: 50,
        images: ['https://res.cloudinary.com/demo/image/upload/sample.jpg'],
    },
    {
        name: 'Girls Round Neck Cotton Top',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish.',
        price: 36,
        category: 'Kids',
        subCategory: 'Topwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: false,
        featured: true,
        stock: 50,
        images: ['https://res.cloudinary.com/demo/image/upload/sample.jpg'],
    },
    {
        name: 'Women Round Neck Cotton Top',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish.',
        price: 30,
        category: 'Women',
        subCategory: 'Topwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: false,
        featured: true,
        stock: 50,
        images: ['https://res.cloudinary.com/demo/image/upload/sample.jpg'],
    },
    {
        name: 'Men Slim Fit Denim Jacket',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish.',
        price: 86,
        category: 'Men',
        subCategory: 'Winterwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: false,
        featured: true,
        stock: 50,
        images: ['https://res.cloudinary.com/demo/image/upload/sample.jpg'],
    },
];
