export const products = [
    {
        name: 'Men Round Neck Pure Cotton T-shirt',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 80,
        category: 'Men',
        subCategory: 'Topwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: true,
        featured: true,
        stock: 50,
        images: ['/assets/frontend_assets/p_img1.png'],
    },
    {
        name: 'Men Tapered Fit Flat-Front Trousers',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 72,
        category: 'Men',
        subCategory: 'Bottomwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: true,
        featured: true,
        stock: 50,
        images: ['/assets/frontend_assets/p_img2_1.png'],
    },
    {
        name: 'Girls Round Neck Cotton Top',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 36,
        category: 'Kids',
        subCategory: 'Topwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: false,
        featured: true,
        stock: 50,
        images: ['/assets/frontend_assets/p_img2_2.png'],
    },
    {
        name: 'Women Round Neck Cotton Top',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 30,
        category: 'Women',
        subCategory: 'Topwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: false,
        featured: true,
        stock: 50,
        images: ['/assets/frontend_assets/p_img2_3.png'],
    },
    {
        name: 'Men Slim Fit Relaxed Denim Jacket',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 86,
        category: 'Men',
        subCategory: 'Winterwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: false,
        featured: true,
        stock: 50,
        images: ['/assets/frontend_assets/p_img2_4.png'],
    },
    {
        name: 'Women Zip-Front Relaxed Fit Jacket',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 78,
        category: 'Women',
        subCategory: 'Winterwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: false,
        featured: true,
        stock: 50,
        images: ['/assets/frontend_assets/p_img2.png'],
    },
    {
        name: 'Men Printed Plain Cotton Shirt',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 49,
        category: 'Men',
        subCategory: 'Topwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: true,
        featured: true,
        stock: 50,
        images: ['/assets/frontend_assets/p_img3.png'],
    },
    {
        name: 'Kids Tapered Slim Fit Trouser',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 56,
        category: 'Kids',
        subCategory: 'Bottomwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: true,
        featured: true,
        stock: 50,
        images: ['/assets/frontend_assets/p_img10.png'],
    },
    {
        name: 'Boy Round Neck Pure Cotton T-shirt',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 26,
        category: 'Kids',
        subCategory: 'Topwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: false,
        featured: true,
        stock: 50,
        images: ['/assets/frontend_assets/p_img11.png'],
    },
    {
        name: 'Women Palazzo Pants with Waist Belt',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 58,
        category: 'Women',
        subCategory: 'Bottomwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: false,
        featured: true,
        stock: 50,
        images: ['/assets/frontend_assets/p_img12.png'],
    },
    {
        name: 'Men Round Neck Pure Cotton T-shirt',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 83,
        category: 'Men',
        subCategory: 'Topwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: false,
        featured: false,
        stock: 50,
        images: ['/assets/frontend_assets/p_img13.png'],
    },
    {
        name: 'Men Tapered Fit Flat-Front Trousers',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 75,
        category: 'Men',
        subCategory: 'Bottomwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: false,
        featured: false,
        stock: 50,
        images: ['/assets/frontend_assets/p_img14.png'],
    },
    {
        name: 'Girls Round Neck Cotton Top',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 39,
        category: 'Kids',
        subCategory: 'Topwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: true,
        featured: false,
        stock: 50,
        images: ['/assets/frontend_assets/p_img15.png'],
    },
    {
        name: 'Women Round Neck Cotton Top',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 33,
        category: 'Women',
        subCategory: 'Topwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: true,
        featured: false,
        stock: 50,
        images: ['/assets/frontend_assets/p_img16.png'],
    },
    {
        name: 'Men Slim Fit Relaxed Denim Jacket',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 89,
        category: 'Men',
        subCategory: 'Winterwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: false,
        featured: false,
        stock: 50,
        images: ['/assets/frontend_assets/p_img17.png'],
    },
    {
        name: 'Women Zip-Front Relaxed Fit Jacket',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 81,
        category: 'Women',
        subCategory: 'Winterwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: false,
        featured: false,
        stock: 50,
        images: ['/assets/frontend_assets/p_img18.png'],
    },
    {
        name: 'Men Printed Plain Cotton Shirt',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 52,
        category: 'Men',
        subCategory: 'Topwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: false,
        featured: false,
        stock: 50,
        images: ['/assets/frontend_assets/p_img19.png'],
    },
    {
        name: 'Kids Tapered Slim Fit Trouser',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 59,
        category: 'Kids',
        subCategory: 'Bottomwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: false,
        featured: false,
        stock: 50,
        images: ['/assets/frontend_assets/p_img20.png'],
    },
    {
        name: 'Boy Round Neck Pure Cotton T-shirt',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 29,
        category: 'Kids',
        subCategory: 'Topwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: true,
        featured: false,
        stock: 50,
        images: ['/assets/frontend_assets/p_img21.png'],
    },
    {
        name: 'Women Palazzo Pants with Waist Belt',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 61,
        category: 'Women',
        subCategory: 'Bottomwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: true,
        featured: false,
        stock: 50,
        images: ['/assets/frontend_assets/p_img22.png'],
    },
    {
        name: 'Men Round Neck Pure Cotton T-shirt',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 86,
        category: 'Men',
        subCategory: 'Topwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: false,
        featured: false,
        stock: 50,
        images: ['/assets/frontend_assets/p_img23.png'],
    },
    {
        name: 'Men Tapered Fit Flat-Front Trousers',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 78,
        category: 'Men',
        subCategory: 'Bottomwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: false,
        featured: false,
        stock: 50,
        images: ['/assets/frontend_assets/p_img24.png'],
    },
    {
        name: 'Girls Round Neck Cotton Top',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 42,
        category: 'Kids',
        subCategory: 'Topwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: false,
        featured: false,
        stock: 50,
        images: ['/assets/frontend_assets/p_img25.png'],
    },
    {
        name: 'Women Round Neck Cotton Top',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 36,
        category: 'Women',
        subCategory: 'Topwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: false,
        featured: false,
        stock: 50,
        images: ['/assets/frontend_assets/p_img26.png'],
    },
    {
        name: 'Men Slim Fit Relaxed Denim Jacket',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 92,
        category: 'Men',
        subCategory: 'Winterwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: true,
        featured: false,
        stock: 50,
        images: ['/assets/frontend_assets/p_img27.png'],
    },
    {
        name: 'Women Zip-Front Relaxed Fit Jacket',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 84,
        category: 'Women',
        subCategory: 'Winterwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: true,
        featured: false,
        stock: 50,
        images: ['/assets/frontend_assets/p_img28.png'],
    },
    {
        name: 'Men Printed Plain Cotton Shirt',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 55,
        category: 'Men',
        subCategory: 'Topwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: false,
        featured: false,
        stock: 50,
        images: ['/assets/frontend_assets/p_img29.png'],
    },
    {
        name: 'Kids Tapered Slim Fit Trouser',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 62,
        category: 'Kids',
        subCategory: 'Bottomwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: false,
        featured: false,
        stock: 50,
        images: ['/assets/frontend_assets/p_img30.png'],
    },
    {
        name: 'Boy Round Neck Pure Cotton T-shirt',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 32,
        category: 'Kids',
        subCategory: 'Topwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: false,
        featured: false,
        stock: 50,
        images: ['/assets/frontend_assets/p_img31.png'],
    },
    {
        name: 'Women Palazzo Pants with Waist Belt',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 64,
        category: 'Women',
        subCategory: 'Bottomwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: false,
        featured: false,
        stock: 50,
        images: ['/assets/frontend_assets/p_img32.png'],
    },
    {
        name: 'Men Round Neck Pure Cotton T-shirt',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 89,
        category: 'Men',
        subCategory: 'Topwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: true,
        featured: false,
        stock: 50,
        images: ['/assets/frontend_assets/p_img33.png'],
    },
    {
        name: 'Men Tapered Fit Flat-Front Trousers',
        description:
            'Premium YARSA apparel with elegant fit, comfortable fabric, and professional finish. Perfect for everyday wear with a clean modern ecommerce feel.',
        price: 81,
        category: 'Men',
        subCategory: 'Bottomwear',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        bestseller: true,
        featured: false,
        stock: 50,
        images: ['/assets/frontend_assets/p_img34.png'],
    },
];
